package apk

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// injected is the file added to the program being built. It is what makes an
// ordinary Go program an Android app without a line of Android in it: a
// shared library has no main to call, so something has to call it, and this
// is that something.
//
// Fallback rather than Main, so that a program which does register its own
// app keeps it — the two can be in the same package and the program's own
// choice wins.
const injected = `//go:build android

// Code generated by antuiapk. DO NOT EDIT.
//
// This file is not on disk: it is handed to the compiler through an overlay
// and exists only for the length of one build.

package main

import "github.com/gabrielluizsf/antui/backend/android/app"

func init() { app.Fallback(main) }
`

// injectedName is what the file is called inside the package being built.
// Nothing is ever written there — the overlay only makes the go command
// believe it is — but the name is chosen to be one nobody would use.
const injectedName = "zz_antuiapk_android_main.go"

// overlayFor writes the injected file and the overlay that points at it,
// returning the overlay's path.
//
// An overlay maps a path the go command would read to a different file on
// disk. Mapping a path that does not exist is how a file is *added* to a
// package without touching the caller's directory — which matters, because
// building someone's program should not write into their source tree.
func overlayFor(cfg *Config, work string) (string, error) {
	src := filepath.Join(work, injectedName)
	if err := os.WriteFile(src, []byte(injected), 0o644); err != nil {
		return "", fmt.Errorf("apk: %w", err)
	}
	doc := struct{ Replace map[string]string }{
		Replace: map[string]string{filepath.Join(cfg.Dir, injectedName): src},
	}
	b, err := json.Marshal(doc)
	if err != nil {
		return "", fmt.Errorf("apk: %w", err)
	}
	path := filepath.Join(work, "overlay.json")
	if err := os.WriteFile(path, b, 0o644); err != nil {
		return "", fmt.Errorf("apk: %w", err)
	}
	return path, nil
}
